### ISSUE TITLE
I don't see a way to encode an Instruction struct

### ISSUE THREAD

**Issue by omarandlorraine** [cr1901/yaxpeax-6502#5]
Given an Instruction struct, representing let's say `adc #$04`, I'm expecting to see some function that's going to return `vec![0x69, 0x04]` or something that can iterate over the bytes encoding the instruction. 

I don't see it though; am I missing something?

**Comment by cr1901** [comment]
`yaxpeax-arch` does not have a trait for encoding, and `yaxpeax-6502` currently does not provide a custom trait or functionality for encoding.

I think an encode trait in `yaxpeax-arch` may be an interesting idea, but if I were to provide encoding, I would do a custom trait for now to get some idea of what a generic encoding trait would look like. However, right now I don't have the spare cycles to implement this.

Leaving this open until I have an idea of how to proceed.

**Comment by cr1901** [comment]
cc: @iximeow Did you ever give an encoding trait some thought, or a crate that's `yaxpeax` in reverse (`xeapxay`?)? I'm not certain the same exact structs/associated types used to implement the `Decoder` trait are appropriate for an `Encoder` trait, but there's _definitely_ appreciable overlap.

**Comment by omarandlorraine** [comment]
We'd have to consider what we should do about instructions that have more than one encoding. And whether or not decoding a byte sequence and then reencoding it needs to yield the same byte sequence or not

**Comment by omarandlorraine** [comment]
>However, right now I don't have the spare cycles to implement this.

I have written a function myself to do this task; would you accept a pull request?

**Comment by cr1901** [comment]
>And whether or not decoding a byte sequence and then reencoding it needs to yield the same byte sequence or not

This is an encoding problem, so data structures from the decoder should not be interested in these details. 
This is the user's responsibility to provide a mapping to the encoder (and the encoder verifies that your supplied byte mapping is a proper alias for the given instruction), IMO.

I've already dealt with this problem with doing `ndisasm` -> `nasm` round trips and handle it manually.

>I have written a function myself to do this task; would you accept a pull request?

Open a PR and I'll take a look.

**Comment by iximeow** [comment]
on encoding in `yaxpeax-arch`: these days i'm pretty comfortable with the `Reader` trait and its operation on `Arch`-defined `Word` types. i think that could pretty reasonably go in the other direction for a `Writer` trait and a corresponding `Encoder` defined for an `Arch`. in particular, i think having a notion of `Word` size is important to be able to encode instructions for weirdly-sized architectures, same as disassembly.

on round-tripping: it would be _nice_ to be able to round-trip bytes through an encoder/decoder, and if there were an `Encoder` trait in `yaxpeax-arch` i definitely would include as implementation guidance to please support round-tripping if possible, and explicitly note if round-tripping is not possible.

i've thought about how such a thing might be possible in x86, where there are also many synonymous instructions - i think the decoder would have to retain f.ex _which_ `mov` opcode was in the original instruction, so there would be many `mov`s, and those `mov`s could simplify to one `mov` _mnemonic_ that client code can operate on. selecting a specific mov _opcode_ would be tricky, but _would_ support round-tripping.

the other reason i still haven't put an `Encoder` trait in `yaxpeax-arch` is i'd like to put a bit of thought in how to expose encoding constraints for the ISA. i would like to be able to provide them in a way that client code (assemblers, etc) could use those rules directly, instead of needing to have their own implementation of f.ex operands that are permissible for an `0x8b` x86-64 `mov`.

so, for these reasons i'd prefer not having an `Encoder` trait in `yaxpeax-arch` _yet_, though i'm very open to one in the future. for now, it's probably suitable as an external crate with intent to fold into `yaxpeax-arch` when things seem "stable enough".

very big fan of the series of crates supporting both directions of instruction encoding! i'll keep an eye on this too and make a note to jot down my scattered thoughts into a crate.

**Comment by cr1901** [comment]
Closed by #6. @iximeow 

>i think the decoder would have to retain f.ex which mov opcode was in the original instruction, 

FWIW, I'm not a huge fan of this being in the `Decoder` trait-proper; there are many applications where you don't need this information, and it can become unwieldy to enforce all `Decoder`s to support it. On the other hand, not mandating it implies nobody will implement such a `DecoderExtensions` trait. So I guess perhaps this should be a breaking change and put in `Decoder`.

>i would like to be able to provide them in a way that client code (assemblers, etc) could use those rules directly, instead of needing to have their own implementation of f.ex operands that are permissible for an 0x8b x86-64 mov.

I'm not ready to publicly release this code, but I have been working on a `Decoder` where this would be _utter hell_ to enforce this `Encoder` constraint via types. The best I promise is that the aggregate types will never return `Operand` variants that are invalid for an `Instruction` via a runtime check. My plan is to do the same for a hypothetical `Encoder` trait because the _combinatorial explosion is real_.
